/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'RunCode': ApiRouteHandler<{ problemId: string; language: string; code: string }, ApiResponse<200, { status: string; runtime: number | unknown; memory: number | unknown; testResults: Array<{ input: string; expected: string; actual: string | unknown; stdout?: string | unknown; stderr: string | unknown; compileOutput: string | unknown; passed: boolean; runtime: number | unknown; errorDetails?: { verdict: string; errorType: string; line: number | unknown; message: string } | unknown }>; passedCases: number; totalCases: number }> | ApiResponse<400, { error: string }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }>, never>
    'MySubmissions': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { submissions: Array<{ id: string; status: string; language: string; runtime: number | unknown; memory: number | unknown; createdAt: string; problem: { id: string; title: string; slug: string; difficulty: string } }> }>, never>
    'GetSubmission': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, {}> | ApiResponse<404, { error: string }>, never>
    'ExecuteSubmission': EventHandler<never, never>
    'CreateSubmission': ApiRouteHandler<{ problemId: string; language: string; code: string }, ApiResponse<202, { submissionId: string; status: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, { topic: 'execute-submission'; data: never }>
    'GetMyStats': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { totalSolved: number; totalSubmissions: number; accuracy: number; byDifficulty: { EASY: number; MEDIUM: number; HARD: number }; recentActivity: Array<unknown> }>, never>
    'ListProblems': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { problems: Array<{ id: string; title: string; slug: string; difficulty: string; tags: Array<string>; _count: { submissions: number } }>; total: number; page: number; limit: number }>, never>
    'GetProblem': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; title: string; slug: string; difficulty: string; description: string; starterCode: unknown; entryPoint: string; judgeMode?: string; tags: Array<string>; examples: unknown | unknown; constraints: string | unknown; testCases: Array<{ id: string; input: string; expected: string; order: number }> }> | ApiResponse<404, { error: string }>, never>
    'CreateProblem': ApiRouteHandler<{ title: string; slug: string; difficulty: 'EASY' | 'MEDIUM' | 'HARD'; description: string; starterCode: unknown; entryPoint: string; problemType: 'array' | 'string' | 'binary_tree' | 'linked_list' | 'matrix' | 'graph'; judgeMode: 'exact' | 'unordered' | 'float' | 'multiline' | 'spj'; spjCode?: string; tags: Array<string>; examples?: unknown; constraints?: string; testCases: Array<{ input: string; expected: string; isHidden: boolean; order: number }> }, ApiResponse<201, { id: string; title: string; slug: string }> | ApiResponse<400, { error: string }> | ApiResponse<403, { error: string }> | ApiResponse<409, { error: string }>, never>
    'GetLeaderboard': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { leaderboard: Array<{ rank: number; userId: string; name: string | unknown; email: string; rating: number; solved: number }> }>, never>
    'LogGreeting': EventHandler<{ requestId: string; greeting: string; processedBy: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'AuthSession': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { user: { id: string; email: string; name: string | unknown; role: string; rating: number; createdAt: string } }> | ApiResponse<401, { error: string }>, never>
    'AuthRegister': ApiRouteHandler<{ email: string; password: string; name?: string }, ApiResponse<201, { token: string; user: { id: string; email: string; name: string | unknown; role: string } }> | ApiResponse<400, { error: string }> | ApiResponse<409, { error: string }>, never>
    'AuthLogin': ApiRouteHandler<{ email: string; password: string }, ApiResponse<200, { token: string; user: { id: string; email: string; name: string | unknown; role: string; rating: number } }> | ApiResponse<400, { error: string }> | ApiResponse<401, { error: string }>, never>
    'AiGetHint': ApiRouteHandler<{ problemId: string; userCode?: string }, ApiResponse<200, { hint: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, never>
    'AiExplain': ApiRouteHandler<{ problemId: string }, ApiResponse<200, { explanation: string; approach: string; keyInsights: Array<string> }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, never>
    'AiCodeFeedback': ApiRouteHandler<{ problemId: string; language: string; code: string }, ApiResponse<200, { feedback: string; timeComplexity: string; spaceComplexity: string; isOptimal?: boolean; improvementTip?: string; interviewNote?: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, never>
    'AiExplainError': ApiRouteHandler<{ problemId: string; language: string; code: string; errorDetails: { verdict: string; errorType: string; line: number | unknown; message: string }; testcase?: { input?: string; expected?: string; received?: string | unknown; isHidden?: boolean } }, ApiResponse<200, { summary: string; rootCause: string; fixSteps: Array<string>; conceptToReview: string; likelyIssue?: string; whyItHappens?: string; debugSteps?: Array<string>; edgeCasesToCheck?: Array<string> }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, { topic: 'greeting-processed'; data: { requestId: string; greeting: string; processedBy: string } }>
  }
    
}